### ISSUE TITLE
BUG: #showtooltip breaks pfUI tooltip

### ISSUE THREAD

**Issue by dein0s** [DennisWG/Roid-Macros#27]
As mentioned in subj - it breaks pfUI tooltip positioning (pfUI tooltip - Dodge)
Also, with `#shotwooltip` ability on the pannel is grayed out like as inactive (not usable).
`/script if false then CastSpellByName("Mind Flay"); end`
![screen1](https://i.imgur.com/CsKEbDR.png)
`#showtooltip Mind Flay`
![screen2](https://i.imgur.com/OvOQSX1.png)

**Comment by DennisWG** [comment]
The #showtooltip sadly doesn't replace the `/script if false then ...` part. This seems to be hardcoded into the client, so I don't think you can ever get rid of it.

As for this breaking pfUI:
I'll try to get a look at it asap! Maybe next weekend if I'm lucky.

**Comment by ivanosh** [comment]
is it possible to use different tooltips with modificators? [mod:shift]
And what about icon change?

**Comment by dein0s** [comment]
@ivanosh it's definitely possible, at least tooltip text can be changed accordingly to spell conditions (including modifiers) with https://github.com/DanielAdolfsson/CleverMacro
not sure about icons tho

**Comment by Road-block** [comment]
Just because the waste of characters bothers me ..  
You can replace `/script if false then CastSpellByName("Mind Flay"); end`  
with `/run --CastSpellByName"Mind Flay"` for the exact same effect at 22 characters less.  
This line is also unrelated to the tooltip, this is put in macros so the actionbutton will show that spell cooldown status.
