### ISSUE TITLE
client freeze

### ISSUE THREAD

**Issue by Nihlo** [DennisWG/Roid-Macros#29]
Thanks for the addon, working great...normally. But whenever I'm in raid and zone in the instance the client freezes and I have to force-close it. Took me a while to track it down to this addon, if it is deactivated, everthing works normally. I'm 100% sure it is exactly this addon...no idea how actually. Not getting any error or a client-crash-report, it just freezes.

**Comment by Solipsismic** [comment]
Same thing happening for me

**Comment by rpuHbI4** [comment]
same. changed back to old version...

**Comment by ignaszewski** [comment]
same, agreed

**Comment by Nihlo** [comment]
@rpuHbI4 to witch version ? the only release is the same isn't it ?

**Comment by dawwet** [comment]
I got the same problem and I've tried to figured it out what causing it for me, and the problem seems to occur when I enter/leaving dungeons and the mouse cursor is hovering over my action bars, then it crashes immediately. 
Addons that Im using https://i.imgur.com/D9qbjl1.png 
Hope this help, awesome addon and great work! 👍

**Comment by Nihlo** [comment]
yeah got that, thanks. The tooltip thingy was pretty cool though

**Comment by DennisWG** [comment]
Thank you for reporting this bug and thank you @dawwet for giving me the details on how to reproduce it!

This should be fixed now on the master branch and in the upcoming 1.3 release!
