### ISSUE TITLE
Conditions

### ISSUE THREAD

**Issue by Oroxzy** [DennisWG/Roid-Macros#33]
Hey very nice Addon btw! i love it!
is it possible to add  [nomod] and [noequipped] to it??

thanks :)

**Comment by DennisWG** [comment]
Hey,
I'm glad you're liking my addon! I'm always looking forward to adding new conditions, but in order to implement them, I have to know what they're supposed to do. Would you mind telling me? :)

**Comment by jeremymeile** [comment]
ok the problem is if i have a macro like this (im using nomod macros in retail too .. its great) its gonna do the [nomod] too if i press any modifier key... in retail wow u can set nomod its very useful! :

/cast [nomod, nocombat, stance:1] Charge; [nomod, nocombat, nocooldown:Charge, stance:2/3] Battle Stance
/cast [stance:3] Intercept; [mod:shift,nocooldown:Intercept,cooldown:Charge,myrawpower>9,stance:1/2] Berserker Stance
/cast [stance:3,harm] Intercept; [mod:shift,harm,nocooldown:Intercept,combat,myrawpower>9,stance:1/2] Berserker Stance
/cast [nomod,stance:1] Rend
/cast [mod:ctrl] Hamstring
/startattack
