### ISSUE TITLE
String expected error w/ Bongos

### ISSUE THREAD

**Issue by lvangh** [DennisWG/Roid-Macros#38]
I'm using the extra macro space with Super Macro to create /emote buttons (for fun) in an additional Bongos bar. When I hover over the buttons, I get this error:

`Interface\Addons\Roid-Macros\Utility.lua:16: bad argument #1 to `find'' (string expected, got nil)`

In short, I create a simple /wave macro using Super Macro, drag that over to a Bongos bar and hover over it and I get the error.

*edit- Possibly not a Bongos issue, seems related to SuperMacro 

Screenshot
https://imgur.com/a/v77zchf

![image](https://user-images.githubusercontent.com/19690096/46190147-3176db00-c2a7-11e8-947d-3e9cde1c0500.png)

**Comment by DennisWG** [comment]
Hey,

I've applied a band-aid fix but I can not guarantee that Super Macro will not blow this Addon up again.
Super Macro really doesn't want to play ball with any other macro addons, which is why I usually suggest uninstalling it when possible.

Anyway, please make sure to re-download Roid-Macros and tell me whether it worked or not.

**Comment by lvangh** [comment]
I just ended up leaving this alone and uninstalled SuperMacro. Thank you for trying.
